const AttributesMap: Map<string, string> = new Map([
  ["ref-accept", "accept"],
  ["ref-accept-charset", "accept-charset"],
  ["ref-accesskey", "accesskey"],
  ["ref-action", "action"],
  ["ref-allow", "allow"],
  ["ref-alt", "alt"],
  ["ref-as", "as"],
  ["ref-async", "async"],
  ["ref-autocapitalize", "autocapitalize"],
  ["ref-autocomplete", "autocomplete"],
  ["ref-autoplay", "autoplay"],
  ["ref-background", "background"],
  ["ref-bgcolor", "bgcolor"],
  ["ref-border", "border"],
  ["ref-capture", "capture"],
  ["ref-charset", "charset"],
  ["ref-checked", "checked"],
  ["ref-cite", "cite"],
  ["ref-class", "class"],
  ["ref-color", "color"],
  ["ref-cols", "cols"],
  ["ref-colspan", "colspan"],
  ["ref-content", "content"],
  ["ref-contenteditable", "contenteditable"],
  ["ref-controls", "controls"],
  ["ref-coords", "coords"],
  ["ref-crossorigin", "crossorigin"],
  ["ref-csp", "csp"],
  ["ref-object-data", "data"],
  ["ref-datetime", "datetime"],
  ["ref-decoding", "decoding"],
  ["ref-default", "default"],
  ["ref-defer", "defer"],
  ["ref-dir", "dir"],
  ["ref-dirname", "dirname"],
  ["ref-disabled", "disabled"],
  ["ref-download", "download"],
  ["ref-draggable", "draggable"],
  ["ref-enctype", "enctype"],
  ["ref-enterkeyhint", "enterkeyhint"],
  ["ref-for", "for"],
  ["ref-form", "form"],
  ["ref-formaction", "formaction"],
  ["ref-formenctype", "formenctype"],
  ["ref-formmethod", "formmethod"],
  ["ref-formvalidate", "formvalidate"],
  ["ref-formtarget", "formtarget"],
  ["ref-headers", "headers"],
  ["ref-height", "height"],
  ["ref-hidden", "hidden"],
  ["ref-high", "high"],
  ["ref-href", "href"],
  ["ref-hreflang", "hreflang"],
  ["ref-http-equiv", "http-equiv"],
  ["ref-id", "id"],
  ["ref-integrity", "integrity"],
  ["ref-inputmode", "inputmode"],
  ["ref-ismap", "ismap"],
  ["ref-itemprop", "itemprop"],
  ["ref-kind", "kind"],
  ["ref-label", "label"],
  ["ref-lang", "lang"],
  ["ref-language", "language"],
  ["ref-loading", "loading"],
  ["ref-list", "list"],
  ["ref-loop", "loop"],
  ["ref-low", "low"],
  ["ref-max", "max"],
  ["ref-maxlength", "maxlength"],
  ["ref-minlength", "minlength"],
  ["ref-media", "media"],
  ["ref-method", "method"],
  ["ref-min", "min"],
  ["ref-multiple", "multiple"],
  ["ref-muted", "muted"],
  ["ref-name", "name"],
  ["ref-novalidate", "novalidate"],
  ["ref-open", "open"],
  ["ref-optimum", "optimum"],
  ["ref-pattern", "pattern"],
  ["ref-ping", "ping"],
  ["ref-placeholder", "placeholder"],
  ["ref-playinline", "playinline"],
  ["ref-poster", "poster"],
  ["ref-preload", "preload"],
  ["ref-readonly", "readonly"],
  ["ref-referrerpolicy", "referrerpolicy"],
  ["ref-rel", "rel"],
  ["ref-required", "required"],
  ["ref-reversed", "reversed"],
  ["ref-role", "role"],
  ["ref-rows", "rows"],
  ["ref-rowspan", "rowspan"],
  ["ref-sandbox", "sandbox"],
  ["ref-scope", "scope"],
  ["ref-selected", "selected"],
  ["ref-shape", "shape"],
  ["ref-size", "size"],
  ["ref-sizes", "sizes"],
  ["ref-slot", "slot"],
  ["ref-span", "span"],
  ["ref-spellcheck", "spellcheck"],
  ["ref-src", "src"],
  ["ref-srcdoc", "srcdoc"],
  ["ref-srclang", "srclang"],
  ["ref-srcset", "srcset"],
  ["ref-start", "start"],
  ["ref-step", "step"],
  ["ref-style", "style"],
  ["ref-tabindex", "tabindex"],
  ["ref-target", "target"],
  ["ref-title", "title"],
  ["ref-translate", "translate"],
  ["ref-type", "type"],
  ["ref-usemap", "usemap"],
  ["ref-value", "value"],
  ["ref-width", "width"],
  ["ref-wrap", "wrap"],
  ["ref-aria-autocomplete", "aria-autocomplete"],
  ["ref-aria-checked", "aria-checked"],
  ["ref-aria-disabled", "aria-disabled"],
  ["ref-aria-errormessage", "aria-errormessage"],
  ["ref-aria-expanded", "aria-expanded"],
  ["ref-aria-haspopup", "aria-haspopup"],
  ["ref-aria-hidden", "aria-hidden"],
  ["ref-aria-invalid", "aria-invalid"],
  ["ref-aria-label", "aria-label"],
  ["ref-aria-level", "aria-level"],
  ["ref-aria-modal", "aria-modal"],
  ["ref-aria-multiline", "aria-multiline"],
  ["ref-aria-multiselectable", "aria-multiselectable"],
  ["ref-aria-orientation", "aria-orientation"],
  ["ref-aria-placeholder", "aria-placeholder"],
  ["ref-aria-pressed", "aria-pressed"],
  ["ref-aria-readonly", "aria-readonly"],
  ["ref-aria-required", "aria-required"],
  ["ref-aria-selected", "aria-selected"],
  ["ref-aria-sort", "aria-sort"],
  ["ref-aria-valuemax", "aria-valuemax"],
  ["ref-aria-valuemin", "aria-valuemin"],
  ["ref-aria-valuenow", "aria-valuenow"],
  ["ref-aria-valuetext", "aria-valuetext"],
  ["ref-aria-busy", "aria-busy"],
  ["ref-aria-live", "aria-live"],
  ["ref-aria-relevant", "aria-relevant"],
  ["ref-aria-atomic", "aria-atomic"],
  ["ref-aria-dropeffect", "aria-dropeffect"],
  ["ref-aria-grabbed", "aria-grabbed"],
  ["ref-aria-activedescendant", "aria-activedescendant"],
  ["ref-aria-colcount", "aria-colcount"],
  ["ref-aria-colindex", "aria-colindex"],
  ["ref-aria-colspan", "aria-colspan"],
  ["ref-aria-controls", "aria-controls"],
  ["ref-aria-describedby", "aria-describedby"],
  ["ref-aria-description", "aria-description"],
  ["ref-aria-details", "aria-details"],
  ["ref-aria-errormessage", "aria-errormessage"],
  ["ref-aria-flowto", "aria-flowto"],
  ["ref-aria-labelledby", "aria-labelledby"],
  ["ref-aria-owns", "aria-owns"],
  ["ref-aria-posinset", "aria-posinset"],
  ["ref-aria-rowcount", "aria-rowcount"],
  ["ref-aria-rowindex", "aria-rowindex"],
  ["ref-aria-rowspan", "aria-rowspan"],
  ["ref-aria-setsize", "aria-setsize"],
  ["ref-aria-atomic", "aria-atomic"],
  ["ref-aria-busy", "aria-busy"],
  ["ref-aria-controls", "aria-controls"],
  ["ref-aria-current", "aria-current"],
  ["ref-aria-describedby", "aria-describedby"],
  ["ref-aria-description", "aria-description"],
  ["ref-aria-details", "aria-details"],
  ["ref-aria-disabled", "aria-disabled"],
  ["ref-aria-dropeffect", "aria-dropeffect"],
  ["ref-aria-errormessage", "aria-errormessage"],
  ["ref-aria-flowto", "aria-flowto"],
  ["ref-aria-grabbed", "aria-grabbed"],
  ["ref-aria-haspopup", "aria-haspopup"],
  ["ref-aria-hidden", "aria-hidden"],
  ["ref-aria-invalid", "aria-invalid"],
  ["ref-aria-keyshortcuts", "aria-keyshortcuts"],
  ["ref-aria-label", "aria-label"],
  ["ref-aria-labelledby", "aria-labelledby"],
  ["ref-aria-live", "aria-live"],
  ["ref-aria-owns", "aria-owns"],
  ["ref-aria-relevant", "aria-relevant"],
  ["ref-aria-roledescription", "aria-roledescription"]
]);

export const ATTRIBUTES_MAP = AttributesMap;

export const REF_ATTRIBUTES_LIST = [
  "ref-data",
  "ref-model",
  "ref-accept",
  "ref-accept-charset",
  "ref-accesskey",
  "ref-action",
  "ref-allow",
  "ref-alt",
  "ref-as",
  "ref-async",
  "ref-autocapitalize",
  "ref-autocomplete",
  "ref-autoplay",
  "ref-background",
  "ref-bgcolor",
  "ref-border",
  "ref-capture",
  "ref-charset",
  "ref-checked",
  "ref-cite",
  "ref-class",
  "ref-color",
  "ref-cols",
  "ref-colspan",
  "ref-content",
  "ref-contenteditable",
  "ref-controls",
  "ref-coords",
  "ref-crossorigin",
  "ref-csp",
  "ref-object-data",
  "ref-datetime",
  "ref-decoding",
  "ref-default",
  "ref-defer",
  "ref-dir",
  "ref-dirname",
  "ref-disabled",
  "ref-download",
  "ref-draggable",
  "ref-enctype",
  "ref-enterkeyhint",
  "ref-for",
  "ref-form",
  "ref-formaction",
  "ref-formenctype",
  "ref-formmethod",
  "ref-formvalidate",
  "ref-formtarget",
  "ref-headers",
  "ref-height",
  "ref-hidden",
  "ref-high",
  "ref-href",
  "ref-hreflang",
  "ref-http-equiv",
  "ref-id",
  "ref-integrity",
  "ref-inputmode",
  "ref-ismap",
  "ref-itemprop",
  "ref-kind",
  "ref-label",
  "ref-lang",
  "ref-language",
  "ref-loading",
  "ref-list",
  "ref-loop",
  "ref-low",
  "ref-max",
  "ref-maxlength",
  "ref-minlength",
  "ref-media",
  "ref-method",
  "ref-min",
  "ref-multiple",
  "ref-muted",
  "ref-name",
  "ref-novalidate",
  "ref-open",
  "ref-optimum",
  "ref-pattern",
  "ref-ping",
  "ref-placeholder",
  "ref-playinline",
  "ref-poster",
  "ref-preload",
  "ref-readonly",
  "ref-referrerpolicy",
  "ref-rel",
  "ref-required",
  "ref-reversed",
  "ref-role",
  "ref-rows",
  "ref-rowspan",
  "ref-sandbox",
  "ref-scope",
  "ref-selected",
  "ref-shape",
  "ref-size",
  "ref-sizes",
  "ref-slot",
  "ref-span",
  "ref-spellcheck",
  "ref-src",
  "ref-srcdoc",
  "ref-srclang",
  "ref-start",
  "ref-step",
  "ref-style",
  "ref-tabindex",
  "ref-target",
  "ref-title",
  "ref-translate",
  "ref-type",
  "ref-type",
  "ref-usemap",
  "ref-value",
  "ref-width",
  "ref-wrap",
  "ref-aria-autocomplete",
  "ref-aria-checked",
  "ref-aria-disabled",
  "ref-aria-errormessage",
  "ref-aria-expanded",
  "ref-aria-haspopup",
  "ref-aria-hidden",
  "ref-aria-invalid",
  "ref-aria-label",
  "ref-aria-level",
  "ref-aria-modal",
  "ref-aria-multiline",
  "ref-aria-multiselectable",
  "ref-aria-orientation",
  "ref-aria-placeholder",
  "ref-aria-pressed",
  "ref-aria-readonly",
  "ref-aria-required",
  "ref-aria-selected",
  "ref-aria-sort",
  "ref-aria-valuemax",
  "ref-aria-valuemin",
  "ref-aria-valuenow",
  "ref-aria-valuetext",
  "ref-aria-busy",
  "ref-aria-live",
  "ref-aria-relevant",
  "ref-aria-atomic",
  "ref-aria-dropeffect",
  "ref-aria-grabbed",
  "ref-aria-activedescendant",
  "ref-aria-colcount",
  "ref-aria-colindex",
  "ref-aria-colspan",
  "ref-aria-controls",
  "ref-aria-describedby",
  "ref-aria-description",
  "ref-aria-details",
  "ref-aria-errormessage",
  "ref-aria-flowto",
  "ref-aria-labelledby",
  "ref-aria-owns",
  "ref-aria-posinset",
  "ref-aria-rowcount",
  "ref-aria-rowindex",
  "ref-aria-rowspan",
  "ref-aria-setsize",
  "ref-aria-atomic",
  "ref-aria-busy",
  "ref-aria-controls",
  "ref-aria-current",
  "ref-aria-describedby",
  "ref-aria-description",
  "ref-aria-details",
  "ref-aria-disabled",
  "ref-aria-dropeffect",
  "ref-aria-errormessage",
  "ref-aria-flowto",
  "ref-aria-grabbed",
  "ref-aria-haspopup",
  "ref-aria-hidden",
  "ref-aria-invalid",
  "ref-aria-keyshortcuts",
  "ref-aria-label",
  "ref-aria-labelledby",
  "ref-aria-live",
  "ref-aria-owns",
  "ref-aria-relevant",
  "ref-aria-roledescription"
];

export default AttributesMap;
